name: Env Deployment pipeline

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

env:
  DOCKER_BUILDKIT: 1

on:
  workflow_dispatch:
    inputs:
      deploy_env:
        description: enviornment name
        type: string #environment 
  repository_dispatch:

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3     
  
  push-cfn:
    name: Push cloudfromation
    runs-on: ubuntu-latest
    needs: [build]
    env:
      GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
    steps:
      - name: Call push cloudformation pipeline
        id: push-cfn
        env:
            ENV_NAME: ${{ inputs.deploy_env }}
        run: |
          curl -L \
          -X POST \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/aqeeleurus/poc-reusable-reply-action/actions/workflows/action.yml/dispatches \
          -d '{"ref":"main","inputs":{"deploy_env":"$ENV_NAME"}}'
        shell: bash
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: ${{ inputs.deploy_env }}
    needs: response-from-push-cfn
    steps:
      - name: deploy
        id: deploy
        env:
            ENV_NAME: ${{ inputs.deploy_env }}
        run: |
          echo "Deploy step running"
        shell: bash

  response-from-push-cfn:
    name: Pushed cloudfromation
    runs-on: ubuntu-latest
    needs: push-cfn
    steps:
      - name: Response from push cloudformation pipeline
        id: pushed-cfn
        if: github.event.action == 'response'
        run: |
          echo "Response received from '${{ github.event.client_payload.repository }}'"
        shell: bash

  # response-from-push-cfn:
  #   name: Pushed cloudfromation
  #   runs-on: ubuntu-latest
  #   env:
  #     GITHUB_TOKEN: ${{ secrets.ACTION_SECRET }}
  #   needs: push-cfn
  #   steps:
  #     - name: Response from push cloudformation pipeline
  #       id: pushed-cfn
  #       run: |
  #         response_data=$(curl -s -X POST \
  #           -H "Authorization: Bearer $GITHUB_TOKEN" \
  #           -H "Accept: application/vnd.github.v3+json" \
  #           https://api.github.com/repos/aqeeleurus/poc-reusable-reply-action/actions/workflows/action.yml/dispatches \
  #           -d '{"ref":"main"}' | jq -r .workflow_run_url)
  #         echo "Response from the Response Workflow: $response_data"
  #       shell: bash